source :rubygems

gem 'sinatra'
gem 'shotgun'
gem 'dm-core'
gem 'dm-validations'
gem 'dm-timestamps'
gem 'dm-migrations'
gem 'dm-sqlite-adapter'
gem 'dm-types'
gem 'haml'
gem 'sass'
gem 'ultraviolet1x', :git => 'git://github.com/grosser/ultraviolet.git'
gem 'sinatra-flash'
gem 'facets'
gem "rack-pagespeed", :git => 'git://github.com/c00lryguy/rack-pagespeed.git', :ref => '376677bb0de9aa428919'
